cv_options:
 resolution:
  - 1920
  - 1080
 window_size:
  - 1280
  - 720

camera_capture:
 left_cam_id: 0
 right_cam_id: 1
 image_count: 50
 image_path: single_camera_images
 stereo_images_path: stereo_camera_images
 stereo_images_count: 50

camera_calibration:
 intrinsic_params_dir: intrinsic_dir
 extrinsic_params_dir: extrinsic_dir
 pattern_size:
  - 10
  - 7
 world_scaling: 1.5 
 single_calibration_error_threshold: 0.3
 stereo_calibration_error_threshold: 0.7
 headless: False

validation:
 pattern_size:
  - 10
  - 7
