name: cc-venv #default if -n not tiven on command line
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10 #because open3d works with 3.10
  - matplotlib
  - numpy
  - pytest
  - pyyaml
  - pandas
  - seaborn
  - gdown
  - click
  - scikit-learn
  - pip: #these are the things that conda channels don't have, so we use pip
      - opencv-contrib-python==4.10.0.84
      - open3d==0.18.0

