name: 'Download Camera Calibration Images'
description: 'Downloads for camera calibration tests'

inputs:
  os:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Check ubuntu cache for calibration images
      if : ${{ contains(inputs.os, 'ubuntu') }}
      run: |
        python -m pip install gdown
        mkdir test_images && cd test_images
        gdown $CC_FILE_ID
        unzip *.zip
        rm *.zip
      shell: bash
      env:
        CC_FILE_ID: "11DnV4eJ260KHSar1_fIcYjrdB4gLQn7g"
    - name: Check windows cache for calibration images
      if : ${{ contains(inputs.os, 'windows') }}
      run: |
        python -m pip install gdown
        New-Item -ItemType Directory -Path "test_images"
        Set-Location -Path "test_images"
        gdown $env:CC_FILE_ID
        Expand-Archive -Path (Get-ChildItem -Filter *.zip).FullName -DestinationPath . -Force
        Remove-Item *.zip
      shell: powershell
      env:
        CC_FILE_ID: "11DnV4eJ260KHSar1_fIcYjrdB4gLQn7g"


