# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Camera-Calibration Tests
on:
  push:

env:
    CC_FILE_ID: ${{ secrets.FILE_ID }}
permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    environment: testing
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: cc-venv
        auto-update-conda: true
        auto-activate-base: false
        channels: conda-forge, loopbio
        channel-priority: flexible
        environment-file: environment.yml
    - name: Download Camera Calibration Images
      uses: ./.github/actions/download-camera-calibration
      with:
        os: ${{ matrix.os }}
      env: 
        CC_FILE_ID: ${{ secrets.FILE_ID }}
    - name: Test with pytest Ubuntu
      if: ${{ contains(matrix.os, 'ubuntu') }}
      run: |
        conda init
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cc-venv
        
        which python
        python -m pytest tests -s --basetemp test_data
    - name: Test with pytest Windows
      if: ${{ contains(matrix.os, 'windows') }}
      run: |
        python -m pytest tests -s --basetemp test_data
